### ISSUE TITLE
Animated Splash screen

### ISSUE THREAD

**Issue by SpDly14** [jahirfiquitiva/Kuper#68]
### Kuper Version

2.3.8

### Describe the feature

The kuper is already great but, it would be the best if animated Splash screen is possible.
Like setting video or any other animated video format in the splash screen.

**Comment by jahirfiquitiva** [comment]
There are no plans of adding such feature as it only might increase the size of the app or complicate its setup.

If you'd like, you could look into Animated Vector Drawables, that way you can keep using a drawable file, instead of needing a video.

Otherwise, Kuper is open-source, so you can access the whole code and modify it to match your needs
