### ISSUE TITLE
Wiki Update 

### ISSUE THREAD

**Issue by missyraja** [jahirfiquitiva/Kuper#85]
### Kuper Version

2.4.6

### Describe the feature

Hey it's been long since the wiki of kuper has been updated. Could you update the how to Wiki so that we don't run into issues. I've had multiple issues that I'm not sure how to fix and frankly I stopped updating my apps.

**Comment by jahirfiquitiva** [comment]
Hi @missyraja 

The wiki is up to date and the setup process hasn't changed much.

The [`How to update`](https://github.com/jahirfiquitiva/Kuper/wiki/How-to-update) page should guide you on how to incrementally update your app.

It is important that you don't skip versions, but apply updates one by one, otherwise you might run into issues for not applying previous updates.

Are there any specific issues you have faced? Feel free to comment them here.

You can also join the [Discord community server](https://discordapp.com/invite/78h7xgj) if you haven't already.

Once there, feel free to post any issues and I will try to help when possible
